package content

import (
	"context"
	"os"
	"path/filepath"
	"regexp"

	"github.com/zanelin/blog/internal/model"
	contentR "github.com/zanelin/blog/internal/repository/content"
)

// photoFilenameRe matches photo filenames generated by the backend
// (8 hex + "-" + 3 hex + ".jpg"). Used to validate paths before deletion
// so a tampered photo.URL can't delete arbitrary files via path traversal.
var photoFilenameRe = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{3}\.jpg$`)

type PhotoService interface {
	List(ctx context.Context) ([]*model.Photo, error)
	Create(ctx context.Context, url, title string, sortOrder int) (*model.Photo, error)
	Delete(ctx context.Context, id int64) error
}

type photoService struct {
	repo contentR.PhotoRepository
}

func NewPhotoService(repo contentR.PhotoRepository) PhotoService {
	return &photoService{repo: repo}
}

func (s *photoService) List(ctx context.Context) ([]*model.Photo, error) {
	return s.repo.List(ctx)
}

func (s *photoService) Create(ctx context.Context, url, title string, sortOrder int) (*model.Photo, error) {
	p := &model.Photo{URL: url, Title: title, SortOrder: sortOrder}
	if err := s.repo.Create(ctx, p); err != nil {
		return nil, err
	}
	return p, nil
}

func (s *photoService) Delete(ctx context.Context, id int64) error {
	photo, err := s.repo.GetByID(ctx, id)
	if err != nil {
		return err
	}
	if err := s.repo.Delete(ctx, id); err != nil {
		return err
	}
	// best-effort: remove the file after the DB record is gone.
	// Validate filename to prevent path traversal from a tampered URL.
	if photo.URL != "" {
		name := filepath.Base(photo.URL)
		if photoFilenameRe.MatchString(name) {
			os.Remove(filepath.Join("uploads/photos", name))
		}
	}
	return nil
}
